### ISSUE TITLE
[Velodrome] zapper doesn't show alchemix's alUSD and alETH tokens locked in velodrome

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#1050]
https://github.com/Zapper-fi/support/issues/251

**Comment by hanaya-zapper** [comment]
![image](https://user-images.githubusercontent.com/87445639/189230663-31c28045-e546-4a10-b478-4178c59db0bb.png)

**Comment by hanaya-zapper** [comment]
zapper doesn't show alchemix's alUSD and alETH tokens locked in velodrome

it may be because velodrome doesn't use [official optimism token list ](https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/master/optimism.tokenlist.json)

but

they have their own list:
https://docs.velodrome.finance/tokenlist.json

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://zapperfi.zendesk.com/agent/tickets/3112" target="_blank">3112</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3112" target="_blank">#3112</a>
                  <div class="pull-right" style="float:right">By: <em>Hanaya &lt;hanaya@zapper.fi&gt;</em></div>
                </div>
              </div>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                        <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                        <div class="panel-body" style="padding: 15px;">
                            <br/>
                            <strong>Wallet Address:&nbsp;</strong>0x116f282adca7a37e59668d80400d2e4277dac80a<br/>
                            <strong>Type Of Issue:&nbsp;</strong>viewing_balance<br/><br/>
                        </div>
                        <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                            Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3112" target="_blank">#3112</a>
                            <div class="pull-right" style="float:right">By: <em>Hanaya &lt;hanaya@zapper.fi&gt;</em></div>
                        </div>
                        </div>

**Comment by immasandwich** [comment]
Confirmed alUSD/USDC appears in `0xd180dd68759a1570a66439548319b94240f309c0`
User in support ticket is still missing LUSD/USDC, looking into it...

**Comment by immasandwich** [comment]
Resolved; user at `0x116f282aDCA7a37E59668d80400D2e4277DaC80A` can now see their LUSD/USDC balances on Velodrome.
