### ISSUE TITLE
The keypress event in a swap blurs the focused input after a small delay.

### ISSUE THREAD

**Issue by cedricwaxwing** [Zapper-fi/studio#1089]
## What happens currently
When inputting an amount in the swap input, the keypress triggers an estimate based on the current value. However, this also blurs the input so that the input is no longer active.
![Aug-07-2022 14-29-55](https://user-images.githubusercontent.com/80348806/183311698-882beec2-d313-4b79-be02-e8819eecf7c0.gif)

## What should happen
The keypress triggered event is very helpful and should still run the same as it does currently, however, it should not remove the active status of the input so that the user can keep typing without having to click back inside of the input.

**Comment by SamIam-0x** [comment]
Thanks for the feedback! We'll look to address this in our swaps update

**Comment by mehdi-loup** [comment]
This is fixed

**Comment by SamIam-0x** [comment]
Nice! Thanks Mehdi!
