### ISSUE TITLE
[Ren] renBTC WBTC sBTC not showing correct. value

### ISSUE THREAD

**Issue by chaojuanlian** [Zapper-fi/studio#1091]
ethereum网络下，
renBTC WBTC sBTC单独显示的币种数量 ≠ renBTC/WBTC/sBTC的汇总数量，该以哪一个数据为准

**Comment by SamIam-0x** [comment]
Translation: Under the ethereum network,
renBTC WBTC sBTC separately displayed currency quantity ≠ renBTC/WBTC/sBTC aggregate quantity, which data should prevail

**Comment by wpoulin** [comment]
Moving away from GH board
