### ISSUE TITLE
[beefy polygon] Not every Beefy vault is showing up

### ISSUE THREAD

**Issue by hanaya-zapper** [Zapper-fi/studio#1120]
<div class="zd-comment" dir="auto"><p dir="auto">Not every Beefy vault is showing up</p></div> <br/>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://zapperfi.zendesk.com/agent/tickets/3299" target="_blank">3299</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3299" target="_blank">#3299</a>
                  <div class="pull-right" style="float:right">By: <em>Hanaya &lt;hanaya@zapper.fi&gt;</em></div>
                </div>
              </div>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                        <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                        <div class="panel-body" style="padding: 15px;">
                            <br/>
                            <strong>Wallet Address:&nbsp;</strong>NA<br/>
                            <strong>Type Of Issue:&nbsp;</strong>NA<br/><br/>
                        </div>
                        <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                            Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3299" target="_blank">#3299</a>
                            <div class="pull-right" style="float:right">By: <em>Hanaya &lt;hanaya@zapper.fi&gt;</em></div>
                        </div>
                        </div>

**Comment by hanaya-zapper** [comment]
Looks like the Quickswap stMATIC-MATIC LP and LDO-MATIC LP farms aren't showing
![Screen Shot 2022-08-09 at 11 36 22 AM](https://user-images.githubusercontent.com/87445639/183735761-68a01c44-9864-4501-ac9f-c47d858d9c59.png)

**Comment by wpoulin** [comment]
We don't have a Uniswap-v2 integration on Polygon yet which is why a bunch of pools on Beefy on Polygon are missing.

**Comment by SamIam-0x** [comment]
oh that is interesting! And that feels like a gap. Will add it to the board
for us to consider

**Comment by SamIam-0x** [comment]
OK I added uniswap-v2 support for polygon as a thing on this board. We can keep this guy open

https://github.com/Zapper-fi/studio/issues/1205
