### ISSUE TITLE
[Beefy polygon] supported boosted Beefy Vaults

### ISSUE THREAD

**Issue by hanaya-zapper** [Zapper-fi/studio#1149]
<div class="zd-comment" dir="auto"><p dir="auto">matic/stmatic - curve</p>
<p dir="auto">- vault address 0xE0570ddFca69E5E90d83Ea04bb33824D3BbE6a85</p>
<p dir="auto">- strategy address- 0x31890c2009E79f6540eF210Eb491db8cF5119a8e</p>
<p dir="auto">matic/stmatic - quickswap</p>
<p dir="auto">- strategy address- 0xED5c4150F867b278866bbAD33e947287cc5a2Ef1</p>
<p dir="auto">- vault address- 0x8829ADf1a9a7facE44c8FAb3Bc454f93F330E492</p></div> <br/>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://zapperfi.zendesk.com/agent/tickets/3333" target="_blank">3333</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3333" target="_blank">#3333</a>
                  <div class="pull-right" style="float:right">By: <em>Hanaya &lt;hanaya@zapper.fi&gt;</em></div>
                </div>
              </div>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                        <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                        <div class="panel-body" style="padding: 15px;">
                            <br/>
                            <strong>Wallet Address:&nbsp;</strong>NA<br/>
                            <strong>Type Of Issue:&nbsp;</strong>NA<br/><br/>
                        </div>
                        <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                            Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3333" target="_blank">#3333</a>
                            <div class="pull-right" style="float:right">By: <em>Hanaya &lt;hanaya@zapper.fi&gt;</em></div>
                        </div>
                        </div>

**Comment by SamIam-0x** [comment]
These are both now added! 

Quickswap stMatic/wMatic: https://zapper.fi/apps/quickswap/token-position/polygon/0x65752c54d9102bdfd69d351e1838a1be83c924c6?addresses[]=0x683199c35f0d18a076f387a7a7bf1daa3f264c49

Curve stMatic/wMatic: https://zapper.fi/apps/curve/token-position/polygon/0xe7cea2f6d7b120174bf3a9bc98efaf1ff72c997d?addresses[]=0x683199c35f0d18a076f387a7a7bf1daa3f264c49

**Comment by SamIam-0x** [comment]
These are both now added! 

Quickswap stMatic/wMatic: https://zapper.fi/apps/quickswap/token-position/polygon/0x65752c54d9102bdfd69d351e1838a1be83c924c6?addresses[]=0x683199c35f0d18a076f387a7a7bf1daa3f264c49

Curve stMatic/wMatic: https://zapper.fi/apps/curve/token-position/polygon/0xe7cea2f6d7b120174bf3a9bc98efaf1ff72c997d?addresses[]=0x683199c35f0d18a076f387a7a7bf1daa3f264c49

**Comment by SamIam-0x** [comment]
so, I was mistaken-- this issue relates to Beefy Finance on polygon. When a user deposits the 2 pool tokens listed above, for stMatic / wMatic from QuickSwap and Curve into a beefy finance vault, that vault does not show up in user's portfolio

More details and test wallet in this zendesk ticket: https://zapperfi.zendesk.com/agent/tickets/3333

cc @wpoulin

**Comment by wpoulin** [comment]
There it is : https://zapper.fi/apps/beefy?network=polygon&tokens%5B0%5D=stMATIC

**Comment by SamIam-0x** [comment]
BAH BAH BAAHHHHH

**Comment by wpoulin** [comment]
'Boosted vaults' are basically partnership made between Beefy and a given app in order to drive liquidity. I investigate quite a bit trying to find boosted vaults addresses but those arent' available from their API, neither from the vault contract on chain. The mapping seems to be hardcoded in their FE, so I've sent them a message asking how could we fetch it. I'm currently waiting for their reply

**Comment by SamIam-0x** [comment]
OK, so it looks like this is now fixed! Closing
