### ISSUE TITLE
[furucombo] Fix furucombo after balance fetcher change

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#1169]

**Comment by immasandwich** [comment]
Dev was concerned about the removal of the balance fetcher class: https://github.com/Zapper-fi/studio/pull/1090#issuecomment-1212884064

Non-issue, just an undocumented new feature with the pattern changes in Studio. See https://zapper.fi/account/0xef8cb659e8b3430d7da41bdc9ecfdcf6bfc1311a for working Furucombo tokens.
