### ISSUE TITLE
Remove rugged lending CREAM assets (KEEP long-term staked, as these were not rugged)

### ISSUE THREAD

**Issue by ethermachine** [Zapper-fi/studio#1224]
This is not done yet..

https://github.com/Zapper-fi/studio/issues/39

**Comment by ethermachine** [comment]
Unfortunately, you have removed also the long term stakes
https://app.cream.finance/stake/cream
https://app.cream.finance/stake/iceCream

Only the lending pools were hacked..

**Comment by ethermachine** [comment]
@mehdi-loup

**Comment by SamIam-0x** [comment]
oh that is annoying, ok, will add to board to fix @ethermachine

**Comment by wpoulin** [comment]
We've removed the lending markets (supply + borrow). Thanks for the report

**Comment by ethermachine** [comment]
@wpoulin the issue now is that everything was removed. But there are several markets that shouldn't have been removed: the long term staking pools:
https://github.com/Zapper-fi/studio/issues/1224#issuecomment-1238611921

**Comment by ethermachine** [comment]
its done now  🙌🏻
