### ISSUE TITLE
[quickswap] USDC / ASTRAFER Pool token when farmed not in Zapper

### ISSUE THREAD

**Issue by hanaya-zapper** [Zapper-fi/studio#1257]
<div class="zd-comment" dir="auto"><p dir="auto">hi there, another problem with farming:</p>
<p dir="auto">USDC / ASTRAFER pair doesn't appear when LP staked for farming, though when tokens just added to pool, it shows it correct</p></div> <br/><p><strong>Attachments:</strong></p><ol><li><a href="https://zapperfi.zendesk.com/attachments/token/DuiQGNINofo9pelwQDV1Qu3PL/?name=Screen+Shot+2022-08-24+at+11.55.21.png" target="_blank">Screen Shot 2022-08-24 at 11.55.21.png</a></li></ol>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://zapperfi.zendesk.com/agent/tickets/3522" target="_blank">3522</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3522" target="_blank">#3522</a>
                  <div class="pull-right" style="float:right">By: <em>Sam &lt;sam@zapper.fi&gt;</em></div>
                </div>
              </div>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                        <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                        <div class="panel-body" style="padding: 15px;">
                            <br/>
                            <strong>Wallet Address:&nbsp;</strong>0x011b0a055E02425461A1ae95B30F483c4fF05bE7<br/>
                            <strong>Type Of Issue:&nbsp;</strong>NA<br/><br/>
                        </div>
                        <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                            Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3522" target="_blank">#3522</a>
                            <div class="pull-right" style="float:right">By: <em>Sam &lt;sam@zapper.fi&gt;</em></div>
                        </div>
                        </div>

**Comment by wpoulin** [comment]
This PR will fix missing quickswap single and dual reward farms => https://github.com/Zapper-fi/zapper-api/pull/8087/files

**Comment by wpoulin** [comment]
FIXED ! 🚀
