### ISSUE TITLE
[Aave-v2] APY incorrect (off by 100x)

### ISSUE THREAD

**Issue by hanaya-zapper** [Zapper-fi/studio#1272]
<div class="zd-comment" dir="auto"><p dir="auto">Borrow rate of WMATIC of Polygon Aave V2:</p>
<ul dir="auto">
<li>Accurate: 15% in https://app.aave.com/markets/</li>
<li>Wrong in Zapper 1300%&nbsp;</li>
</ul>
<p dir="auto">You can see attachements.</p></div> <br/><p><strong>Attachments:</strong></p><ol><li><a href="https://zapperfi.zendesk.com/attachments/token/qSBdcbnossFfiidwhj4yRJf0c/?name=Zapper.png" target="_blank">Zapper.png</a></li><li><a href="https://zapperfi.zendesk.com/attachments/token/C2bHXXF6YvSSfIvLoBxJjVj9Q/?name=Aave.png" target="_blank">Aave.png</a></li></ol>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://zapperfi.zendesk.com/agent/tickets/3551" target="_blank">3551</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3551" target="_blank">#3551</a>
                  <div class="pull-right" style="float:right">By: <em>Sam &lt;sam@zapper.fi&gt;</em></div>
                </div>
              </div>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                        <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                        <div class="panel-body" style="padding: 15px;">
                            <br/>
                            <strong>Wallet Address:&nbsp;</strong>0x77929b20172302a8eaa20b5485c67a4a357024a9<br/>
                            <strong>Type Of Issue:&nbsp;</strong>NA<br/><br/>
                        </div>
                        <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                            Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3551" target="_blank">#3551</a>
                            <div class="pull-right" style="float:right">By: <em>Sam &lt;sam@zapper.fi&gt;</em></div>
                        </div>
                        </div>

**Comment by SamIam-0x** [comment]
this is fixed!

**Comment by SamIam-0x** [comment]
this is fixed!

**Comment by SamIam-0x** [comment]
this is fixed!
