### ISSUE TITLE
[Velodrome] incorrect value for staked Velodrome pool tokens

### ISSUE THREAD

**Issue by hanaya-zapper** [Zapper-fi/studio#1293]
<div class="zd-comment" dir="auto"><p dir="auto">hi there, i started staking with VELODROME. though, zapper reports incorrect data about staked amounts and prices. please, check screenshots from VELODROME itself and zapper reported data:</p>
<p dir="auto">1. staked OP: 4420, staked VELO: 168196</p>
<p dir="auto">2. reported by zapper OP: 6309 and VELO: 117834</p>
<p dir="auto">also, OP price reported 1.76, though actual price 1.16, and VELO price reported 0.095 and actual price 0.027</p></div> <br/><p><strong>Attachments:</strong></p><ol><li><a href="https://zapperfi.zendesk.com/attachments/token/5n2gPJXzkpaWf40DBCchxhvRC/?name=Screen+Shot+2022-08-22+at+10.00.55.png" target="_blank">Screen Shot 2022-08-22 at 10.00.55.png</a></li><li><a href="https://zapperfi.zendesk.com/attachments/token/p3DMFknQL7iTWQubjH08dQd9d/?name=Screen+Shot+2022-08-22+at+10.01.25.png" target="_blank">Screen Shot 2022-08-22 at 10.01.25.png</a></li></ol>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://zapperfi.zendesk.com/agent/tickets/3477" target="_blank">3477</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3477" target="_blank">#3477</a>
                  <div class="pull-right" style="float:right">By: <em>Sam &lt;sam@zapper.fi&gt;</em></div>
                </div>
              </div>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                        <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                        <div class="panel-body" style="padding: 15px;">
                            <br/>
                            <strong>Wallet Address:&nbsp;</strong>0x011b0a055E02425461A1ae95B30F483c4fF05bE7<br/>
                            <strong>Type Of Issue:&nbsp;</strong>NA<br/><br/>
                        </div>
                        <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                            Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3477" target="_blank">#3477</a>
                            <div class="pull-right" style="float:right">By: <em>Sam &lt;sam@zapper.fi&gt;</em></div>
                        </div>
                        </div>

**Comment by immasandwich** [comment]
Seems ok now?
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/22452366/187579439-0a7ff219-72c5-4bf3-9390-a81089a1f407.png">
<img width="1746" alt="image" src="https://user-images.githubusercontent.com/22452366/187579464-811fc4f0-75a8-4476-8c64-bb8861d06e06.png">
