### ISSUE TITLE
[Llama Airforce] Support auraBAL on Llama Airforce

### ISSUE THREAD

**Issue by hanaya-zapper** [Zapper-fi/studio#1305]
<div class="zd-comment" dir="auto"><div>
<div>Zapper - https://zapper.fi/apps/llama-airforce?network=ethereum</div>
<div>&nbsp;</div>
<div>auraBAL Vault - <a href="https://etherscan.io/address/0xd6fc1ecd9965ba9cac895654979564a291c74c29" rel="noreferrer">0xd6fc1ecd9965ba9cac895654979564a291c74c29</a></div>
</div>
<div>
<div>
<div>auraBAL Strategy - <a href="https://etherscan.io/address/0xca7b5b6a9b135fc7e29ba7bc5d4cca936395025c" rel="noreferrer">0xca7b5b6a9b135fc7e29ba7bc5d4cca936395025c</a></div>
</div>
</div></div> <br/>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://zapperfi.zendesk.com/agent/tickets/3570" target="_blank">3570</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3570" target="_blank">#3570</a>
                  <div class="pull-right" style="float:right">By: <em>Sam &lt;sam@zapper.fi&gt;</em></div>
                </div>
              </div>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                        <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                        <div class="panel-body" style="padding: 15px;">
                            <br/>
                            <strong>Wallet Address:&nbsp;</strong>0x37de2f99bf85ebc078cfcfe6bbc6b58f5d8c0b65<br/>
                            <strong>Type Of Issue:&nbsp;</strong>NA<br/><br/>
                        </div>
                        <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                            Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3570" target="_blank">#3570</a>
                            <div class="pull-right" style="float:right">By: <em>Sam &lt;sam@zapper.fi&gt;</em></div>
                        </div>
                        </div>

**Comment by immasandwich** [comment]
Incoming https://github.com/Zapper-fi/studio/pull/1317
