### ISSUE TITLE
[PlutusDAO] add support for plvGLP vault

### ISSUE THREAD

**Issue by hanaya-zapper** [Zapper-fi/studio#1306]
<div class="zd-comment" dir="auto"><p dir="auto">plvGLP Vault - <a href="https://arbiscan.io/address/0x4E5Cf54FdE5E1237e80E87fcbA555d829e1307CE" rel="noreferrer">0x4E5Cf54FdE5E1237e80E87fcbA555d829e1307CE</a></p></div> <br/>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://zapperfi.zendesk.com/agent/tickets/3571" target="_blank">3571</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3571" target="_blank">#3571</a>
                  <div class="pull-right" style="float:right">By: <em>Sam &lt;sam@zapper.fi&gt;</em></div>
                </div>
              </div>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                        <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                        <div class="panel-body" style="padding: 15px;">
                            <br/>
                            <strong>Wallet Address:&nbsp;</strong>0x37de2f99bf85ebc078cfcfe6bbc6b58f5d8c0b65<br/>
                            <strong>Type Of Issue:&nbsp;</strong>NA<br/><br/>
                        </div>
                        <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                            Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3571" target="_blank">#3571</a>
                            <div class="pull-right" style="float:right">By: <em>Sam &lt;sam@zapper.fi&gt;</em></div>
                        </div>
                        </div>

**Comment by SamIam-0x** [comment]
Hello @tonzgao ! 

We recently got a bug report that PlutusDAO integration does not support plvGLP vault. Is this something you've looked at?

I've added it to our public github board for the devs to look into, but if you have interest, feel free to take a look!

Public board: https://github.com/Zapper-fi/studio/projects/1

**Comment by tonzgao** [comment]
so regarding plutus, there's a discussion here about it https://discord.com/channels/647279669388771329/998267024516067438/998267316280246323. Essentially that I'm not really following the plutus ecosystem atm.

the plvGLP does seem interesting, so if I decide to start using it I can do an implementation then. That being said, I'm more or less not trading eth-usd until the merge, so it may be a while.

**Comment by SamIam-0x** [comment]
No worries at all! Was just reaching out in case it was of interest

I think @immasandwich actually took it pretty quick anyway: https://github.com/Zapper-fi/studio/pull/1307
