### ISSUE TITLE
[Morpho] Fix utilization ratio on Morpho (looks to be off by 100x)

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#1387]
![image](https://user-images.githubusercontent.com/43358952/189459645-a20010d4-6b37-466b-94de-a93e5149a16c.png)

Utilization ratio showing 0.51%, when it looks like it should be 51%

**Comment by SamIam-0x** [comment]
@julien-devatom hey Julian-- thanks for your work on the Morpho integration! I was QA'ing it today (a bit behind!), and noticed that the Utilization Rate looks like its off by 100x

Is this something you'd be interested in updating?

**Comment by julien-devatom** [comment]
Oh yeah nice shot! I'm working on a pr to improve the displaying of the morpho integration to have sth like aave or compound on Zapper and I'll implement this fix in my pr, thanks!

**Comment by SamIam-0x** [comment]
Awesome to hear, and much appreciated!

**Comment by immasandwich** [comment]
Fix coming here: https://github.com/Zapper-fi/studio/pull/1390
