### ISSUE TITLE
[Yearn] The position on yearn is inaccurate. Ac...

### ISSUE THREAD

**Issue by hanaya-zapper** [Zapper-fi/studio#1397]
<div class="zd-comment" dir="auto"><p dir="auto">Hello,</p>
<p dir="auto">1. The position on yearn is inaccurate. Actual balance (according to yearn.finance) is 292.0568 yvCurve-stETH and the APY is currently 6.99%. Zapper shows a balance of 267.48 yvCurve-stETH and an APY of 0.07%. Why would that be?</p>
<p dir="auto">2. Is there a way to set the bundle as the home page?</p>
<p dir="auto">Thanks and Kind Regards,</p>
<p dir="auto">shakem8</p></div> <br/>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://zapperfi.zendesk.com/agent/tickets/3697" target="_blank">3697</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3697" target="_blank">#3697</a>
                  <div class="pull-right" style="float:right">By: <em>Hanaya &lt;hanaya@zapper.fi&gt;</em></div>
                </div>
              </div>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                        <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                        <div class="panel-body" style="padding: 15px;">
                            <br/>
                            <strong>Wallet Address:&nbsp;</strong>NA<br/>
                            <strong>Type Of Issue:&nbsp;</strong>NA<br/><br/>
                        </div>
                        <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                            Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3697" target="_blank">#3697</a>
                            <div class="pull-right" style="float:right">By: <em>Hanaya &lt;hanaya@zapper.fi&gt;</em></div>
                        </div>
                        </div>

**Comment by hanaya-zapper** [comment]
![Screen Shot 2022-09-12 at 1 05 31 PM](https://user-images.githubusercontent.com/87445639/189746896-4bd2b40c-59e4-4a2d-881b-c0434b5d7650.png)

**Comment by SamIam-0x** [comment]
I think this was fixed today by this PR @immasandwich

**Comment by hanaya-zapper** [comment]
Looks like the value is accurate within the app breakdown but it shows incorrect on the app card
<img width="762" alt="Screen Shot 2022-09-13 at 11 05 07 AM" src="https://user-images.githubusercontent.com/87445639/189977334-171b8796-cf77-4349-bd2a-5d4e6048c9df.png">

**Comment by JForsaken** [comment]
Closing, since we show the actual vault token balance -- Yearn shows the underlying token balance, which ours is also correct
