### ISSUE TITLE
[1inch] Staked 1inch APR incorrect

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#1439]
"how do you guys calculate Staked 1inch (0x0f85a912448279111694f4ba4f85dc641c54b594) APR? the APR value is clearly wackadoodle (3000% or something)... I'm trying to figure out how to get the raw claimable numbers myself, but no success yet..."

**Comment by wpoulin** [comment]
I'll put this on pause temporary until Synthetix's helpers will be migrated to template. I investigated the issues and those will be easy to fix once 1inch is migrated to template. 

When periodFinish >= Now, APY should be 0

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://zapperfi.zendesk.com/agent/tickets/3866" target="_blank">3866</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3866" target="_blank">#3866</a>
                  <div class="pull-right" style="float:right">By: <em>Hanaya &lt;hanaya@zapper.fi&gt;</em></div>
                </div>
              </div>

**Comment by hanaya-zapper** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                        <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                        <div class="panel-body" style="padding: 15px;">
                            <br/>
                            <strong>Wallet Address:&nbsp;</strong>NA<br/>
                            <strong>Type Of Issue:&nbsp;</strong>NA<br/><br/>
                        </div>
                        <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                            Zendesk:&nbsp;<a href="https://zapperfi.zendesk.com/agent/tickets/3866" target="_blank">#3866</a>
                            <div class="pull-right" style="float:right">By: <em>Hanaya &lt;hanaya@zapper.fi&gt;</em></div>
                        </div>
                        </div>

**Comment by SamIam-0x** [comment]
this was also highglihted by Min on Discord today

https://discord.com/channels/647279669388771329/650654989202489354/1029427758620745808

**Comment by SamIam-0x** [comment]
@wpoulin hey, im still seeing super high APR for 1inch governance in the API, at 3600%. Reference address: https://zapper.fi/account/0x0f85a912448279111694f4ba4f85dc641c54b594?

Output attached

response_1666048321940.json

**Comment by SamIam-0x** [comment]
{
  "items": [
    {
      "balance": "1",
      "balanceUSD": "3998.74048632",
      "collection": {
        "name": "Cool Cats NFT",
        "description": "Cool Cats is a collection of 9,999 randomly generated and stylistically curated NFTs that exist on the Ethereum Blockchain. Cool Cat holders can participate in exclusive events such as NFT claims, raffles, community giveaways, and more. Remember, all cats are cool, but some are cooler than others.\r\n\r\n- [Cool Cats Collabs](https://opensea.io/collection/cool-cats-collabs)\r\n- [Cool Cats Events](https://opensea.io/collection/cool-cats-events)\r\n- [Cool Cats Achievements](https://opensea.io/collection/cool-cats-achievements)\r\n- [Cool Cats Originals](https://opensea.io/collection/cool-cats-originals)",
        "logoImageUrl": "https://lh3.googleusercontent.com/LIov33kogXOK4XZd2ESj29sqm_Hww5JSdO7AFn5wjt8xgnJJ0UpNV9yITqxra3s_LMEW1AnnrgOVB_hDpjJRA1uF4skI5Sdi_9rULi8=s120",
        "cardImageUrl": "https://lh3.googleusercontent.com/61EdoKNXN0ontZ5A2D-EZsPkam6T2ZMY2uBSBsM6xDhaXZoo9B6v58qF9_9SAj3VaPuPPgc82b2x7-3O4dwA8GvnfkxmMxgW8TPGlFs=s300",
        "bannerImageUrl": "https://lh3.googleusercontent.com/H4Iu36XQNJqVlF99-0BuQna0sUlUcIrHt97ss3le_tAWw8DveEBfTktX3S0bP6jpC9FhN1CKZjoYzZFXpWjr1xZfQIwSSLeDjdi0jw=s2500",
        "nftStandard": "erc721",
        "floorPriceEth": "2.9499",
        "marketCap": "29366.2545",
        "openseaId": "cool-cats-nft",
        "socialLinks": [
          {
            "name": "opensea",
            "label": "Opensea",
            "url": "https://opensea.io/collection/cool-cats-nft",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/opensea.png"
          },
          {
            "name": "website",
            "label": "Website",
            "url": "http://coolcatsnft.com",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/website.png"
          },
          {
            "name": "discord",
            "label": "Discord",
            "url": "https://discord.gg/X6A4AXrKaR",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/discord.png"
          },
          {
            "name": "medium",
            "label": "Medium",
            "url": "https://medium.com/coolcatsnft",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/medium.png"
          },
          {
            "name": "twitter",
            "label": "Twitter",
            "url": "https://twitter.com/coolcatsnft",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/twitter.png"
          }
        ],
        "stats": {
          "hourlyVolumeEth": "0",
          "hourlyVolumeEthPercentChange": null,
          "dailyVolumeEth": "8.18",
          "dailyVolumeEthPercentChange": -3.764705882352941,
          "weeklyVolumeEth": "159.94729999999998",
          "weeklyVolumeEthPercentChange": -71.174789670831,
          "monthlyVolumeEth": "1185.8436444444444",
          "monthlyVolumeEthPercentChange": 79.82733857374095,
          "totalVolumeEth": "64825.93875046114"
        }
      }
    },
    {
      "balance": "2",
      "balanceUSD": "872.284674",
      "collection": {
        "name": "Forgotten Runes Warriors Guild",
        "description": "Forgotten Runes Warriors Guild\r\n\r\n[Sister Collections](https://opensea.io/collection/forgottenrunes)",
        "logoImageUrl": "https://lh3.googleusercontent.com/q1MtHAoWMZWLYE-7On4Az1JrliltRSbR-nZNoPXYslrJnJi1E0EJvEhQ6tarAPVUIjPtpZEgGB7tlFa1ItUSHOBhd4OtOj6fih2cpZw=s120",
        "cardImageUrl": "https://lh3.googleusercontent.com/mxWj7mA60BTBJWBSwh3Hyq_0lA7qtJB2ErdsKrSkPnckLuPgcP62qA5oxA0kPvGSYW9-SWnCTnb6c9f9UkMiBReHJA8imzdCJ_0OaA=s300",
        "bannerImageUrl": "https://lh3.googleusercontent.com/9mnzoCl-AX9g8fEPamzYQ9zOC0HCTQyXmNnOucTmeAmtNA1OSWZhoou9WvYVXNT3c6-xICotdiD2RxHTCpEK4i8gpxLjtzVQEHYcUVk=s2500",
        "nftStandard": "erc721",
        "floorPriceEth": "0.28",
        "marketCap": "4480",
        "openseaId": "forgottenruneswarriorsguild",
        "socialLinks": [
          {
            "name": "opensea",
            "label": "Opensea",
            "url": "https://opensea.io/collection/forgottenruneswarriorsguild",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/opensea.png"
          },
          {
            "name": "website",
            "label": "Website",
            "url": "https://forgottenrunes.com",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/website.png"
          },
          {
            "name": "discord",
            "label": "Discord",
            "url": "https://discord.gg/forgottenrunes",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/discord.png"
          }
        ],
        "stats": {
          "hourlyVolumeEth": "0",
          "hourlyVolumeEthPercentChange": null,
          "dailyVolumeEth": "1.2106",
          "dailyVolumeEthPercentChange": -67.54945585160564,
          "weeklyVolumeEth": "36.13849999999999",
          "weeklyVolumeEthPercentChange": 192.36696912553703,
          "monthlyVolumeEth": "58.7297044444444",
          "monthlyVolumeEthPercentChange": 72.82766098363471,
          "totalVolumeEth": "772.221831302094"
        }
      }
    },
    {
      "balance": "2",
      "balanceUSD": "237.94160032",
      "collection": {
        "name": "Chain Runners XR",
        "description": "[Minting now!](https://somnet.chainrunners.xyz)\n\nChain Runners XR is the newest addition to the Chain Runners Universe. Your XR is your player token to be used across the vast web of digital experiences known as the metaverse. Play as your runner and dance between the ever-blurring lines of the physical and digital world. This is the foundation of a 3D Runnerverse.",
        "logoImageUrl": "https://lh3.googleusercontent.com/sybedFw9L2TORXuksKNHt59AV_uC3NQIuIXbD_ry10zbFM5ZL-Zi8GTwoySLCKEVLUHSh4J2-9faeh-MTc7L6EvSUXVS-mxnqgZe=s120",
        "cardImageUrl": "https://lh3.googleusercontent.com/2CozPZPouq8f0wLMo_3ZTA2dwnKqCBbw9xpbGS1h8GYDFOzPaYtJBwjM5CkfuRhaQPQP8sLUQWggjyJP5q1eFx4AjcppZNyx0Bzb=s300",
        "bannerImageUrl": "https://lh3.googleusercontent.com/5e43oRbsOJjnCIgNPT_09xKaBY2PPffmiaafiPykrlG6hFmcYoER5HAiT4Tj-vkSWuBSvyfk1xH5zInAPDGznxNQiUKMx2DspGX75L4=s2500",
        "nftStandard": "erc721",
        "floorPriceEth": "0.013",
        "marketCap": "161.642",
        "openseaId": "chain-runners-xr",
        "socialLinks": [
          {
            "name": "opensea",
            "label": "Opensea",
            "url": "https://opensea.io/collection/chain-runners-xr",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/opensea.png"
          },
          {
            "name": "website",
            "label": "Website",
            "url": "https://chainrunners.xyz/",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/website.png"
          },
          {
            "name": "discord",
            "label": "Discord",
            "url": "https://discord.gg/chainrunners",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/discord.png"
          }
        ],
        "stats": {
          "hourlyVolumeEth": "0",
          "hourlyVolumeEthPercentChange": null,
          "dailyVolumeEth": "0",
          "dailyVolumeEthPercentChange": null,
          "weeklyVolumeEth": "0.1844",
          "weeklyVolumeEthPercentChange": -61.66399866946634,
          "monthlyVolumeEth": "1.86779424444",
          "monthlyVolumeEthPercentChange": -65.31680231766417,
          "totalVolumeEth": "67.88621841515709"
        }
      }
    },
    {
      "balance": "1",
      "balanceUSD": "226.945624",
      "collection": {
        "name": "Chain Runners",
        "description": "Chain Runners are Mega City renegades 100% stored and generated on chain.\r\n\r\nVisit http://chainrunners.xyz to find out more.",
        "logoImageUrl": "https://lh3.googleusercontent.com/3vScLGUcTB7yhItRYXuAFcPGFNJ3kgO0mXeUSUfEMBjGkGPKz__smtXyUlRxzZjr1Y5x8hz1QXoBQSEb8wm4oBByeQC_8WOCaDON4Go=s120",
        "cardImageUrl": null,
        "bannerImageUrl": "https://lh3.googleusercontent.com/8MKiOEUA3COVcXKzhj54Q5eP0GP9NDOFsumbkiQ2KokimqYGlfTxLKei60ZUG_ipq-VZ5_D2rGZAjxmOVEIVSJaezvrwZe2IywOyEQ=s2500",
        "nftStandard": "erc721",
        "floorPriceEth": "0.1724",
        "marketCap": "1724",
        "openseaId": "chain-runners-nft",
        "socialLinks": [
          {
            "name": "website",
            "label": "Website",
            "url": "http://chainrunners.xyz",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/website.png"
          },
          {
            "name": "discord",
            "label": "Discord",
            "url": "https://discord.gg/f3sk2u4uKN",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/discord.png"
          },
          {
            "name": "twitter",
            "label": "Twitter",
            "url": "https://twitter.com/chain_runners",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/twitter.png"
          }
        ],
        "stats": {
          "hourlyVolumeEth": "0",
          "hourlyVolumeEthPercentChange": null,
          "dailyVolumeEth": "0",
          "dailyVolumeEthPercentChange": -100,
          "weeklyVolumeEth": "1.1971",
          "weeklyVolumeEthPercentChange": -50.7973695026716,
          "monthlyVolumeEth": "7.707518000000001",
          "monthlyVolumeEthPercentChange": -64.65852981595698,
          "totalVolumeEth": "6344.502966999716"
        }
      }
    },
    {
      "balance": "1",
      "balanceUSD": "183.44125656",
      "collection": {
        "name": "ShinseiGalverse",
        "description": "Shinsei Galverse is a collection of 8,888 Gals shooting across space and time to bring a project of peace to all cultures and people.\r\n\r\nWAGMAA - we're gonna make an anime! Join the team in Tokyo as we set out to turn Shinsei Galverse into a real anime production. Have your say in the story, art, and development direction of Shinsei Galverse!\r\n\r\nInspired by nostalgic showa-era anime. Made with love by Emi, Ayaka, Devin, & Jack.\r\n\r\nVisit [galverse.art](https://galverse.art) for more details.",
        "logoImageUrl": "https://lh3.googleusercontent.com/8-v8WDS6DOJPj3GUKcWmWlytTCP3i9QRE9K7YVayIBhhSJIlJGyMQhYx-haXZF543jwZG_EYAuXSxBfUxgLDbmbRtejsKB-P8C8Iaw=s120",
        "cardImageUrl": "https://lh3.googleusercontent.com/vQpC7aNzx0DHnLEfStnGJsOenVlbCOAm-36-T_gFABdIdIFyHcUxp2P16kN2r9Fi9eBJiElFpQ1paU_AwkQcWE_-L917k4SV2e_JmQ=s300",
        "bannerImageUrl": "https://lh3.googleusercontent.com/so2MC-8lei43fKI6W9dkrCSTc78HqGWylN9yi6pJoxm64mp8anTEWkr4513SQ1St-QpyBqgbaRRu-Hrq5G9XqJReq5nl-C6aAGlA4Jg=s2500",
        "nftStandard": "erc721",
        "floorPriceEth": "0.0869",
        "marketCap": "772.3672",
        "openseaId": "galverse",
        "socialLinks": [
          {
            "name": "opensea",
            "label": "Opensea",
            "url": "https://opensea.io/collection/galverse",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/opensea.png"
          },
          {
            "name": "website",
            "label": "Website",
            "url": "https://www.galverse.art/",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/website.png"
          },
          {
            "name": "discord",
            "label": "Discord",
            "url": "https://discord.gg/Galverse",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/discord.png"
          }
        ],
        "stats": {
          "hourlyVolumeEth": "0",
          "hourlyVolumeEthPercentChange": null,
          "dailyVolumeEth": "0.5861999999999999",
          "dailyVolumeEthPercentChange": null,
          "weeklyVolumeEth": "7.166089999999999",
          "weeklyVolumeEthPercentChange": 187.86298761553945,
          "monthlyVolumeEth": "17.78143",
          "monthlyVolumeEthPercentChange": -19.896057446550827,
          "totalVolumeEth": "2674.53828973536"
        }
      }
    },
    {
      "balance": "2",
      "balanceUSD": "78.80984",
      "collection": {
        "name": "Chain Runners: Gear",
        "description": "",
        "logoImageUrl": "https://i.seadn.io/gcs/files/dd7891b501952577b46619256fb896eb.png?w=500&auto=format",
        "cardImageUrl": null,
        "bannerImageUrl": "https://i.seadn.io/gcs/files/7a5ba685b67aeaff6ba5281e9cbe5dd8.png?w=500&auto=format",
        "nftStandard": "erc1155",
        "floorPriceEth": "0.0089",
        "marketCap": "36.846",
        "openseaId": "chain-runners-gear",
        "socialLinks": [
          {
            "name": "opensea",
            "label": "Opensea",
            "url": "https://opensea.io/collection/chain-runners-gear",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/opensea.png"
          }
        ],
        "stats": {
          "hourlyVolumeEth": "0",
          "hourlyVolumeEthPercentChange": null,
          "dailyVolumeEth": "0",
          "dailyVolumeEthPercentChange": null,
          "weeklyVolumeEth": "0",
          "weeklyVolumeEthPercentChange": -100,
          "monthlyVolumeEth": "0.1445",
          "monthlyVolumeEthPercentChange": null,
          "totalVolumeEth": "0.14450000000000002"
        }
      }
    },
    {
      "balance": "2",
      "balanceUSD": "26.448048",
      "collection": {
        "name": "Forgotten Babies Wizard Orphanage",
        "description": "10,000 Forgotten Babies who found themselves in an orphanage that trains youngsters in the magical arts. \nAdopt a baby today and change their life!",
        "logoImageUrl": "https://lh3.googleusercontent.com/Wmzx3HGbow88_3QybHooa1bK6eEa49r8ruxfPi8BcZyLKuRmT6jeW85qwrWO50i2kF625kqzQ2gDtkpKA-q2MmAaMrgxWooYkwXuwMQ=s120",
        "cardImageUrl": null,
        "bannerImageUrl": "https://lh3.googleusercontent.com/DRfmYG5J-dHvHCv_TrrF5r6BejwsMDDJHCHVnqgyb4Si5DVEqLJpVH0T0TJGMFA_Xi9Hf9m3q4pGO_jbBGLolVj88sbwfEYgorkCMA=s2500",
        "nftStandard": "erc721",
        "floorPriceEth": "0.009",
        "marketCap": "90",
        "openseaId": "babywizards",
        "socialLinks": [
          {
            "name": "opensea",
            "label": "Opensea",
            "url": "https://opensea.io/collection/babywizards",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/opensea.png"
          },
          {
            "name": "website",
            "label": "Website",
            "url": "http://forgottenbabies.com",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/website.png"
          },
          {
            "name": "twitter",
            "label": "Twitter",
            "url": "https://twitter.com/BabyWizards",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/twitter.png"
          }
        ],
        "stats": {
          "hourlyVolumeEth": "0",
          "hourlyVolumeEthPercentChange": null,
          "dailyVolumeEth": "0",
          "dailyVolumeEthPercentChange": null,
          "weeklyVolumeEth": "0.18190000000000003",
          "weeklyVolumeEthPercentChange": 1719.0000000000002,
          "monthlyVolumeEth": "0.6529000000000003",
          "monthlyVolumeEthPercentChange": 10.010278184973663,
          "totalVolumeEth": "55.70893820578943"
        }
      }
    },
    {
      "balance": "1",
      "balanceUSD": "8.01456",
      "collection": {
        "name": "Forgotten Runes Comics",
        "description": "Forgotten Runes Comics - Issue #0 readable on June 20th",
        "logoImageUrl": "https://openseauserdata.com/files/62c387ee5f33fd2f410cac1d34ad4c17.png",
        "cardImageUrl": null,
        "bannerImageUrl": null,
        "nftStandard": "erc1155",
        "floorPriceEth": "0.0079",
        "marketCap": "44.7535",
        "openseaId": "forgottenrunescomics",
        "socialLinks": [
          {
            "name": "opensea",
            "label": "Opensea",
            "url": "https://opensea.io/collection/forgottenrunescomics",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/opensea.png"
          },
          {
            "name": "website",
            "label": "Website",
            "url": "https://forgottenrunes.com",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/website.png"
          },
          {
            "name": "twitter",
            "label": "Twitter",
            "url": "https://twitter.com/forgottenrunes",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/twitter.png"
          }
        ],
        "stats": {
          "hourlyVolumeEth": "0",
          "hourlyVolumeEthPercentChange": null,
          "dailyVolumeEth": "0",
          "dailyVolumeEthPercentChange": null,
          "weeklyVolumeEth": "0",
          "weeklyVolumeEthPercentChange": -100,
          "monthlyVolumeEth": "0.02966",
          "monthlyVolumeEthPercentChange": -75.12162388860929,
          "totalVolumeEth": "1.42443"
        }
      }
    },
    {
      "balance": "1",
      "balanceUSD": "1.61493384",
      "collection": {
        "name": "Nimrodz",
        "description": "nimNIMNIMnimnimnimnimNIMnimnimnimNIMNIMnimNIMnimnimnim",
        "logoImageUrl": "https://lh3.googleusercontent.com/lRF77cDqj0WBtiwcoBTaMkPvJSZm5aKrRUhvwmUNjYx8psDok5U6089N48g7QJgkzmnuB13I3e2z60FKY350qgT_XPYgbkTdqw2QWA=s120",
        "cardImageUrl": "https://lh3.googleusercontent.com/FM9BqThefy_8oahr-nvWnv9YYsy09C4ivH99uLRhXL3915VZKavlFR1nwe_nkX-DSWislbIL_m055FH-u8Zm1a8LQWscF7AuumdvDsc=s300",
        "bannerImageUrl": "https://lh3.googleusercontent.com/-NovdK8xPsVfzyfQU7KVW9lc0l_m_bkuLyzUzk5dXuaHVCF6iL26-o1tNoRFL-hIG2KF8D0il8XnkjGTrZBZQZibgHVN3yp-nLaqZQ=s2500",
        "nftStandard": "erc721",
        "floorPriceEth": "0.001",
        "marketCap": "10",
        "openseaId": "nimrodz",
        "socialLinks": [
          {
            "name": "opensea",
            "label": "Opensea",
            "url": "https://opensea.io/collection/nimrodz",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/opensea.png"
          },
          {
            "name": "website",
            "label": "Website",
            "url": "https://www.nimrodz.io/",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/website.png"
          },
          {
            "name": "twitter",
            "label": "Twitter",
            "url": "https://twitter.com/nimrodzNFT",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/twitter.png"
          }
        ],
        "stats": {
          "hourlyVolumeEth": "0",
          "hourlyVolumeEthPercentChange": null,
          "dailyVolumeEth": "0",
          "dailyVolumeEthPercentChange": null,
          "weeklyVolumeEth": "0",
          "weeklyVolumeEthPercentChange": null,
          "monthlyVolumeEth": "0.001",
          "monthlyVolumeEthPercentChange": 0,
          "totalVolumeEth": "17.8665642796899"
        }
      }
    },
    {
      "balance": "2",
      "balanceUSD": "0",
      "collection": {
        "name": "0xFriends",
        "description": "Different Tribe - Same Invisibility. 5K 0xFriends Hiding in the Metaverse.",
        "logoImageUrl": "https://lh3.googleusercontent.com/vhtKqraxu4YCIBoykORxI98syT-ceiRpp4zX-EmaZRZMUQMOiRp1ZsCpnKs6tmo8zlGxc96LIKiVkWx2zwh-YuSTum_MV1QjK6sv=s120",
        "cardImageUrl": null,
        "bannerImageUrl": "https://lh3.googleusercontent.com/NAYlb1K0ey6GfmP_JLcD53zQVtI3ix6jG6YLOzOPFOhnKpKRh1WhtDRNtt1Fay0OAxUPYo8yBTazIbD3u16my_S2IE40BK4kZts32hU=s2500",
        "nftStandard": "erc721",
        "floorPriceEth": null,
        "marketCap": null,
        "openseaId": "0xfriends",
        "socialLinks": [
          {
            "name": "opensea",
            "label": "Opensea",
            "url": "https://opensea.io/collection/0xfriends",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/opensea.png"
          },
          {
            "name": "website",
            "label": "Website",
            "url": "https://0xfriends.co",
            "logoUrl": "https://storage.googleapis.com/zapper-fi-assets/logos/website.png"
          }
        ],
        "stats": {
          "hourlyVolumeEth": "0",
          "hourlyVolumeEthPercentChange": null,
          "dailyVolumeEth": "0",
          "dailyVolumeEthPercentChange": null,
          "weeklyVolumeEth": "0",
          "weeklyVolumeEthPercentChange": null,
          "monthlyVolumeEth": "0",
          "monthlyVolumeEthPercentChange": null,
          "totalVolumeEth": "0.0019"
        }
      }
    },
    {
      "balance": "4",
      "balanceUSD": "0",
      "collection": {
        "name": "ENS: Ethereum Name Service",
        "description": "Ethereum Name Service (ENS) domains are secure domain names for the decentralized world. ENS domains provide a way for users to map human readable names to blockchain and non-blockchain resources, like Ethereum addresses, IPFS hashes, or website URLs. ENS domains can be bought and sold on secondary markets.",
        "logoImageUrl": "https://storage.googleapis.com/zapper-fi-assets/nft/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/unnamed8.png",
        "cardImageUrl": null,
        "bannerImageUrl": "https://storage.googleapis.com/zapper-fi-assets/nft/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/1500x5006.jpeg",
        "nftStandard": "erc721",
        "floorPriceEth": "0.00001",
        "marketCap": "27.02344",
        "openseaId": "ens",
        "socialLinks": [],
        "stats": {
          "hourlyVolumeEth": "0",
          "hourlyVolumeEthPercentChange": null,
          "dailyVolumeEth": "125.34119367896416",
          "dailyVolumeEthPercentChange": 46.453017401618304,
          "weeklyVolumeEth": "1269.9611703019132",
          "weeklyVolumeEthPercentChange": -51.043162600432886,
          "monthlyVolumeEth": "32377.369348838234",
          "monthlyVolumeEthPercentChange": 213.3187576163176,
          "totalVolumeEth": "76424.90661695015"
        }
      }
    },
    {
      "balance": "1",
      "balanceUSD": "0",
      "collection": {
        "name": "Zapper Core",
        "description": "",
        "logoImageUrl": "https://lh3.googleusercontent.com/PGOFkoHkMYUYVScsojUISMCvCAQcAguV90rIwRRoDKC0FObrwmrTxO-nyg4UzVmaKkpZitCXyV2WDvYq0uuQ34xbIti2qeLLxhQ4Mzw=s120",
        "cardImageUrl": null,
        "bannerImageUrl": null,
        "nftStandard": "erc721",
        "floorPriceEth": "0",
        "marketCap": "0",
        "openseaId": "zapper-core",
        "socialLinks": [],
        "stats": {
          "hourlyVolumeEth": "0",
          "hourlyVolumeEthPercentChange": null,
          "dailyVolumeEth": "0",
          "dailyVolumeEthPercentChange": null,
          "weeklyVolumeEth": "0",
          "weeklyVolumeEthPercentChange": null,
          "monthlyVolumeEth": "0",
          "monthlyVolumeEthPercentChange": null,
          "totalVolumeEth": "0"
        }
      }
    }
  ],
  "cursor": "MC0yNjc2OQ=="
}

**Comment by SamIam-0x** [comment]
{
  "balances": {
    "0x399e0ae23663f27181ebb4e66ec504b3aab25541": {
      "products": [
        {
          "label": "Governance",
          "assets": [
            {
              "type": "contract-position",
              "address": "0x0f85a912448279111694f4ba4f85dc641c54b594",
              "network": "ethereum",
              "appId": "1inch",
              "groupId": "governance",
              "tokens": [
                {
                  "metaType": "supplied",
                  "id": "737",
                  "networkId": 1,
                  "address": "0x111111111117dc0aa78b770fa6a738034120c302",
                  "name": "1INCH Token",
                  "symbol": "1INCH",
                  "decimals": 18,
                  "coingeckoId": "1inch",
                  "status": "approved",
                  "hide": false,
                  "canExchange": true,
                  "verified": true,
                  "updatedAt": "2022-10-18T01:45:02.450Z",
                  "createdAt": "2022-05-18T12:54:47.695Z",
                  "price": 0.571522,
                  "dailyVolume": 22762680.8824415,
                  "totalSupply": "1500000000",
                  "networkEnumValue": "ethereum",
                  "type": "base-token",
                  "network": "ethereum",
                  "balance": 152.13180686871635,
                  "balanceRaw": "152131806868716345638",
                  "balanceUSD": 86.9466745252225
                }
              ],
              "dataProps": {
                "liquidity": 144085.1725212879,
                "isActive": false,
                "dailyROI": 0.09937684615848319,
                "weeklyROI": 0.6956379231093823,
                "yearlyROI": 36.272548847846366
              },
              "displayProps": {
                "label": "1INCH",
                "secondaryLabel": {
                  "type": "dollar",
                  "value": 0.571522
                },
                "images": [
                  "https://storage.googleapis.com/zapper-fi-assets/tokens/ethereum/0x111111111117dc0aa78b770fa6a738034120c302.png"
                ],
                "statsItems": [
                  {
                    "label": "APR",
                    "value": {
                      "type": "pct",
                      "value": 3627.2548847846365
                    }
                  },
                  {
                    "label": "Liquidity",
                    "value": {
                      "type": "dollar",
                      "value": 144085.1725212879
                    }
                  }
                ]
              },
              "balanceUSD": 86.9466745252225
            }
          ],
          "meta": []
        }
      ],
      "meta": [
        {
          "label": "Total",
          "value": 86.9466745252225,
          "type": "dollar"
        },
        {
          "label": "Assets",
          "value": 86.9466745252225,
          "type": "dollar"
        },
        {
          "label": "Debt",
          "value": 0,
          "type": "dollar"
        }
      ]
    }
  }
}
