### ISSUE TITLE
Long Pending PR Review for pSTAKE zapper Integration

### ISSUE THREAD

**Issue by vedantd** [Zapper-fi/studio#1442]
A review of a PR is pending since a long time. https://github.com/Zapper-fi/studio/pull/1381
Raising an issue since requested review a while ago.

**Comment by vedantd** [comment]
https://github.com/Zapper-fi/studio/pull/1381

**Comment by immasandwich** [comment]
Hey @vedantd! Apologies for the delays, the team was occupied all week with other priorities. I’m gonna have a chance to review tomorrow or over the weekend.

**Comment by vedantd** [comment]
Appreciate it ! Thank you. Looking forward.
