### ISSUE TITLE
[Snowball] vault outage on avalanche

### ISSUE THREAD

**Issue by hanaya-zapper** [Zapper-fi/studio#1513]
https://app.datadoghq.com/monitors/79465792?q=appid%3Asnowball%2Cerrortype%3Aother%2Cgroupid%3Avault%2Cnetwork%3Aavalanche%2Ctype%3Aapp-token&live=1m

**Comment by immasandwich** [comment]
Resolved with https://github.com/Zapper-fi/zapper-api/pull/8505
