### ISSUE TITLE
[Lido] fix wseETH on L2s

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#1555]
The base token is showing up in portfolios that hold it (example on Arbitrum: https://zapper.fi/account/0x83c2f22173d88eec48ac457b646b11f0b8b350fb)
However, wseETH pools are not showing up, such as Balancers WETH/wseETH pool (https://arbitrum.balancer.fi/#/pool/0xfb5e6d0c1dfed2ba000fbc040ab8df3615ac329c000000000000000000000159); exmaple wallet that holds a pool token on Balancer ARbitrum, not shwoing in thier portfolio: https://zapper.fi/account/0x35822d37ce82be9785107df56a428a2883f8dd11

**Comment by immasandwich** [comment]
Resolved. It was a Balancer V2 bug.
