### ISSUE TITLE
[Angle] "santoken" outage on ethereum

### ISSUE THREAD

**Issue by hanaya-zapper** [Zapper-fi/studio#1561]
https://app.datadoghq.com/monitors/79465792?q=appid%3Aangle%2Cerrortype%3Aother%2Cgroupid%3Asantoken%2Cnetwork%3Aethereum%2Ctype%3Aapp-token&live=1m

Test address: 0xcf263cee139763114faafc5f52865135412f50ec

**Comment by wpoulin** [comment]
Moving away from GH board
