### ISSUE TITLE
"Contribution Guide" link in readme leads to a 404

### ISSUE THREAD

**Issue by zeJabun** [Zapper-fi/studio#196]
Should it lead to: https://github.com/Zapper-fi/studio/blob/main/CONTRIBUTING.md ? 🤓

<img width="1071" alt="Screen Shot 2022-04-20 at 10 41 35 PM" src="https://user-images.githubusercontent.com/86205416/164361021-17ea71b7-3416-4c1d-8489-76c4306a5216.png">

**Comment by mehdi-loup** [comment]
@zeJabun That's correct, feel free to open a pr!
