### ISSUE TITLE
Add vaults - CRV/ETH and AuraBAL

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#2139]
https://zapperfi.zendesk.com/agent/tickets/5366

Crv/ETH Vault: 0x245186CaA063b13d0025891c0d513aCf552fB38E

auraBAL Vault: 0x44B6A414e73fb7387Ca250F44D7e43cD7d6992c2

**Comment by wpoulin** [comment]
Moving away from GH board
