### ISSUE TITLE
Beefy | | ethereum | Can’t see beefy Token on Ethereum

the token‘ cont...

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#2176]
Can’t see beefy Token on Ethereum

the token‘ cont...
Can’t see beefy Token on Ethereum

the token‘ contract address is

0xe50e2fe90745A8510491F89113959a1EF01AD400

It is the tri curve LP token staked on beefy
https://zapperfi.zendesk.com/agent/#/tickets/5056

**Comment by wpoulin** [comment]
Moving away from GH board
