### ISSUE TITLE
Concentrator / Aladdin | | ethereum | Hi

I see that you have support for AladdinDAO and...

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#2199]
Hi

I see that you have support for AladdinDAO and...
Hi

I see that you have support for AladdinDAO and its Concentrator.

I have funds in the Concentrator's ETH-pETH harvester but they aren't showing up

Is there an error here - do you support the harvester vaults?

Thanks for any help

Mark
https://zapperfi.zendesk.com/agent/#/tickets/5462

**Comment by wpoulin** [comment]
Moving away from GH board
