### ISSUE TITLE
Arbitrum missing from uniswapp-v3 app balance

### ISSUE THREAD

**Issue by olivierb2** [Zapper-fi/studio#2218]
Dear team,

I'm trying to make request on https://api.zapper.fi/v2/apps/uniswap-v3/balances in order to get arbitrum balance on uniswap-v3. While this same request works for another address on Ethereum, it gives the following result on Arbitrum. 

~~~
{
	"balances": {
		"0xxxxx": {
			"products": [],
			"meta": [
				{
					"label": "Total",
					"value": 0,
					"type": "dollar"
				},
				{
					"label": "Assets",
					"value": 0,
					"type": "dollar"
				},
				{
					"label": "Debt",
					"value": 0,
					"type": "dollar"
				}
			]
		}
	}
}
~~~

Also, it seems that specifying "networks[]" doesn't change anything, even if I put invalid data.

**Comment by immasandwich** [comment]
For an Arbitrum balance, make sure you hit `https://api.zapper.fi/v2/apps/uniswap-v3/balances?addresses[]=0xWHATEVER&network=arbitrum`

**Comment by olivierb2** [comment]
Oh, this is a documentation mistake maybe ? I tried with networks[] according to this page.
https://studio.zapper.fi/docs/apis/api-syntax#parameters-1
