### ISSUE TITLE
| Trader Joe V2 | | Missing pools on Arbitrum

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#2245]
Seems to me that there's some missing trader joe v...
Seems to me that there's some missing trader joe v2 posistions.

Here's the response of your API, there's only 1 trader joe v2 position here, but I have another LP position. Which is this one: https://traderjoexyz.com/arbitrum/pool/v2/ETH/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8/15

https://zapperfi.zendesk.com/agent/#/tickets/5622

**Comment by immasandwich** [comment]
We weren't including all of the _bins_ for each TJ v2 pool. Now we do!
