### ISSUE TITLE
| Llama Airforce | | Claimables still showing post-claim

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#2257]
Still shows deposited amount after withdraw
Still shows deposited amount after withdraw
https://zapperfi.zendesk.com/agent/#/tickets/5653

**Comment by SamIam-0x** [comment]
cc @0xAlunara - not sure if you want to tackle this, but getting user reports of persisting Llama Airforce claimables after a user claimed them.

example wallet: https://zapper.xyz/account/0xFdbBfB0Fe2986672af97Eca0e797D76A0bbF35c9/protocols/ethereum/llama-airforce

**Comment by SamIam-0x** [comment]
we've added this to our board to investigate and fix

**Comment by 0xAlunara** [comment]
Could this be a cache related issue?

The merkle depositor can be found at `0x0ed7d0497194fc029ae02223fec6d4d567696f17`, and every 2 weeks rewards will be airdropped. Today, at the moment of writing, we'll be airdropping new rewards. You can check if a user has claimed by executing the `isClaimed` read method on the contract. This user's merkle proof contains `"index":1640,"amount":"0x1de6da613cb2ef0000"`. That amount corresponds to the roughly `551.59` cvxCRV as shown on his portfolio. Checking the user's index shows he has indeed claimed his rewards about 9 days ago: https://etherscan.io/tx/0x1f0640c3da3948604dba501047e1cc61a32fc45bd49a74c2eb52c764db17e6b8:

![image](https://user-images.githubusercontent.com/88008691/217189177-49e23549-15e2-49c2-9335-040feae0d67a.png)

I tried looking at this before, but couldn't figure out how fast Zapper would clear the cache and call `isClaimed` again.

**Comment by SamIam-0x** [comment]
@wpoulin can you take a look?
