### ISSUE TITLE
| Qi Dao | | Missing vault position on Optimism: https://app.ma...

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#2266]
Missing vault position on Optimism: https://app.ma...
Missing vault position on Optimism: https://app.mai.finance/vaults/10/beefy-aave-weth/199
https://zapperfi.zendesk.com/agent/#/tickets/5675

**Comment by wpoulin** [comment]
One of the underlying of this vault is a beefy vault. We aren't able to resolve the position because the Beefy API doesn't return underlying for vault with address `0x8e2cdf8c6477439b7c989e86b917d80871b92339`

**Comment by wpoulin** [comment]
Moving away from GH board
