### ISSUE TITLE
Carbon Defi (new Bancor) | integrate app

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#2361]
Carbon Whitepaper: https://www.carbondefi.xyz/whitepaper/
Carbon Litepaper: https://carbondefi.xyz/litepaper
Carbon Simulator: https://github.com/bancorprotocol/carbon-simulator 
Website: https://www.carbondefi.xyz/

**Comment by wpoulin** [comment]
Moving away from GH board
