### ISSUE TITLE
Sturdy | missing collateral assets

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#2389]
Missing collatearl assets from Convex; should be showing up in this wallet: https://zapper.xyz/account/nevercrypto.eth

Looking at contract, Method getReserveList does have all the assets listed on there, so is weird: https://etherscan.io/address/0xa422ca380bd70eef876292839222159e41aaee17#readProxyContract

**Comment by wpoulin** [comment]
Moving away from GH board
