### ISSUE TITLE
Bug: INV positions disappeared in FiRM

### ISSUE THREAD

**Issue by webmass** [Zapper-fi/studio#2740]
Hi
Context: Inverse Finance - FiRM
Market: INV

An update was made recently to zapper studio to add the informations about the DBR token claimable rewards on that market.
It seems now that positions for this market don't show anymore on Zapper, other markets are unaffected.

Address example: 0xAAc0aa431c237C2C0B5f041c8e59B3f1a43aC78F
https://zapper.xyz/account/0xAAc0aa431c237C2C0B5f041c8e59B3f1a43aC78F/protocols/ethereum/inverse-firm

Issue: A position in the INV market should show with INV deposits and DBR rewards.

Details on the position:
https://app.zerion.io/0xaac0aa431c237c2c0b5f041c8e59b3f1a43ac78f/overview/inverse
https://debank.com/profile/0xAAc0aa431c237C2C0B5f041c8e59B3f1a43aC78F

**Comment by wpoulin** [comment]
Everything looks fine. I guess it wasn't showing properly earlier today right ?
![image](https://github.com/Zapper-fi/studio/assets/18474228/89199375-e0f1-4a1d-867e-940926eb7c38)

**Comment by webmass** [comment]
> Everything looks fine. I guess it wasn't showing properly earlier today right ?
> ![image](https://github.com/Zapper-fi/studio/assets/18474228/89199375-e0f1-4a1d-867e-940926eb7c38)
> 

No, the screenshot shows the cvxCrv market, but there should be an INV market showing as well, with INV deposits and DBR rewards.

**Comment by webmass** [comment]
Please let me know

**Comment by wpoulin** [comment]
The positions for INV market is missing. I'll add it to my todo

**Comment by SamIam-0x** [comment]
@webmass 

FYI we launched a way for anyone to build an integration with Zapper without needing Zapper devs to work on it, via our open GitHub repo called Zapper Studio

Anyone can write the integration, so could be someone on the core team, a community member, or a freelancer; they just need to know a little javascript/typescript and a little bit about how smart contracts work (but not a SC engineer or anything). Once a pull request is submitted to that repo, Zapper devs will review it and provide any feedback. If no feedback, we can approve and merge, and balances will be populated!

Documentation for how to write an integration: https://studio.zapper.xyz/

**Comment by SamIam-0x** [comment]
also closing this

**Comment by webmass** [comment]
> @webmass
> 
> FYI we launched a way for anyone to build an integration with Zapper without needing Zapper devs to work on it, via our open GitHub repo called Zapper Studio
> 
> Anyone can write the integration, so could be someone on the core team, a community member, or a freelancer; they just need to know a little javascript/typescript and a little bit about how smart contracts work (but not a SC engineer or anything). Once a pull request is submitted to that repo, Zapper devs will review it and provide any feedback. If no feedback, we can approve and merge, and balances will be populated!
> 
> Documentation for how to write an integration: https://studio.zapper.xyz/

Hi,

Yes I'm aware, I already contributed twice.

The issue mentioned here is in fact related to my lastest contribution where the purpose was to add the rewards part in a market, the contribution was reviewed and approved, but now the market does not appear anymore.

The problem is that it's not possible to test the UI and I couldn't find a way to test the data either.

So when there is a bug in production the zapper team does not help? Also closing the issue while the bug is still there is a bit surprising.

**Comment by SamIam-0x** [comment]
oop sorry, didn't mean to close it when there was an outstanding issue!

**Comment by SamIam-0x** [comment]
and apologies for my delayed response! Enabling testing locally is something we want to introduce in the future, and recognize it is frustrating to not have it

The Zapper team does help for issues in prod, but it does come down to prioritization; if its an easy fix, the team can potentially hop on it. Though, if it was take awhile for the team to get added, it likely will get bumped for other items on the list.

We can try to get to this next week

**Comment by wpoulin** [comment]
It's working like a charm now ! @webmass 
<img width="1086" alt="Screenshot 2023-07-28 at 10 12 16 PM" src="https://github.com/Zapper-fi/studio/assets/18474228/32be0cc5-5e1d-4d4c-8a5e-dd7dd11153f9">

**Comment by webmass** [comment]
> It's working like a charm now ! @webmass <img alt="Screenshot 2023-07-28 at 10 12 16 PM" width="1086" src="https://user-images.githubusercontent.com/18474228/256958717-32be0cc5-5e1d-4d4c-8a5e-dd7dd11153f9.png">

Thanks!
