### ISSUE TITLE
integrate frax lend positions into App section

### ISSUE THREAD

**Issue by Web3fix** [Zapper-fi/studio#2944]
Can we get frax lending positions integrated into zapper?

https://app.frax.finance/fraxlend/available-pairs

I don't know how to do this but hoping someone here can?

Frax is a top 100 market cap protect with over half a billion in tvl so it's not a small project

**Comment by SamIam-0x** [comment]
Hello there! We actually do support Frax Lend! You can see them here - https://zapper.xyz/apps/ethereum/frax-lend?tab=assets&appPrimaryGroup=Lending&page=1

Is there a particular one that is missing? Can look into it if so

**Comment by Web3fix** [comment]
Hi thanks for the reply.

Fraxlend for lending and borrowing doesn't show up correctly.

For example:
codymaverick.eth on zapper is
https://zapper.xyz/account/0x49c9186D4885BadEf3e0B8efCd104C376af81F31?tab=apps 

It shows the users deposit of the LSD sfrxETH as collateral but it doesn't show that this user has Frax lemt out as well.


The summary of his 300k lending position is here:

https://facts.frax.finance/fraxlend/users/0x49c9186d4885badef3e0b8efcd104c376af81f31


Debank confirms the 300k usd equivalent position:
https://debank.com/profile/0x49c9186d4885badef3e0b8efcd104c376af81f31/

**Comment by Web3fix** [comment]
Hi, just wanted to follow up on this.
Is this something you need contribution from the frax devs on?
In the two links above(zapper vs debank) you can see the difference is quite significant

Zapper correctly shows the nft floor value but misses the large fraxlend deposit

**Comment by SamIam-0x** [comment]
hey sorry for the delay! We'll get it added this week

**Comment by SamIam-0x** [comment]
OK lending supply positions are up; adding debt today/tomorrow cc @wpoulin

**Comment by wpoulin** [comment]
It's fixed ! Let me know if there's anything else, otherwise I'll close the issue  @Web3fix

**Comment by Web3fix** [comment]
Thanks!
