### ISSUE TITLE
[StakeDAO] sdFXS gauge

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#37]
from canny.io - https://features.zapper.fi/protocol-requests/p/stakedao-sdfxs-gauge

StakeDAO sdFXS
===============================
Address: 0x402F878BDd1f5C66FdAF0fabaBcF74741B68ac36
Symbol: sdFXS
Description: Basically locked FXS on StakeDAO
FXS price : https://www.coingecko.com/en/coins/frax-share
sdFXS price: Basically 1-to-1 with FXS. True price is on Curve https://curve.fi/factory/100
StakeDAO sdFXS Gauge
===============================
Address: 0xF3C6e8fbB946260e8c2a55d48a5e01C82fD63106
Symbol: sdFXS-gauge
Description: Deposited sdFXS. Earns FXS and SDT rewards
https://lockers.stakedao.org/
Underlying token (sdFXS): 0x402F878BDd1f5C66FdAF0fabaBcF74741B68ac36
sdFXS Gauge price: Basically 1-to-1 with FXS. True price is on Curve https://curve.fi/factory/100
Price info:
FXS: https://www.coingecko.com/en/coins/frax-share
SDT: https://www.coingecko.com/en/coins/stake-dao
Deposited Balance
call balanceOf(<USER ADDRESS) on 0xF3C6e8fbB946260e8c2a55d48a5e01C82fD63106
Rewards
FXS: call claimable_reward(<USER ADDRESS, 0x3432B6A60D23Ca0dFCa7761B7ab56459D9C964D0) on 0xF3C6e8fbB946260e8c2a55d48a5e01C82fD63106
SDT: call claimable_reward(<USER ADDRESS, 0x73968b9a57c6E53d41345FD57a6E6ae27d6CDB2F) on 0xF3C6e8fbB946260e8c2a55d48a5e01C82fD63106
Thank you

**Comment by wpoulin** [comment]
Moving away from GH board
