### ISSUE TITLE
Remove rugged CREAM assets

### ISSUE THREAD

**Issue by SamIam-0x** [Zapper-fi/studio#39]
From Canny: 

[](https://zapper.canny.io/admin/feedback/report-bugs/p/rugged-cream-assets?boards=report-bugs)after CREAM got rugged, the assets used as collaterals and the debt stopped appearing on my wallet, which was the right thing. Today it suddenly reappeared though, which is very confusing because these assets are still lost - illiquid and useless

**Comment by ethermachine** [comment]
would be great if something can be done about this.. the hack was 1 year ago...🙈😖
