### ISSUE TITLE
Tokens on Cronos seem not display correctly

### ISSUE THREAD

**Issue by CronosLabsDev** [Zapper-fi/studio#641]
Expect other Cronos tokens (e.g. [VVS](https://zapper.fi/token/cronos/0x2d03bece6747adc00e1a131bba1469c15fd11e03/VVS), [TONIC](https://zapper.fi/token/cronos/0xdd73dea10abc2bff99c60882ec5b2b81bb1dc5b2/TONIC)) to display like [CRO](https://zapper.fi/token/cronos/0x0000000000000000000000000000000000000000/CRO)
Any advice on it please, thank you 🙏

**Comment by xdrdak** [comment]
@CronosLabsDev should be all good now.
